name: 'Fast Forward Merge'
description: 'Merge a pull request by fast forwarding the target branch.'
author: 'Sequoia PGP'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  merge:
    description: >
      Whether to actually merge the pull request or only check whether
      fast forwarding is possible.

      If true, the action will fast forward the target branch, if
      possible.  If false, the action will only post a comment
      indicating whether it is possible to fast forward the target
      branch.
    default: false
  merge-method:
    description: >
      When merging, whether fast forwarding the branch or creating a
      merge commit.

      If merge-commit, a merge commit is created. Otherwise (the default),
      the branch is fast forwarded.
    default: fast-forward
  merge-author:
    description: >
      The user to use for the merge commit in case of `merge-commit`.

      If set to triggerer, the user who triggered the action is used.
      If set to pr-author, the user who opened the pull request is used.
      If set to fixed, the user specified by `merge-user-name` and
      `merge-user-email` is used.
      If set to none (default), no user is set.

      This option is only required if `merge` is true and `merge-method`
      is merge-commit.
    default: none
  merge-user-name:
    description: >
      The user to use for the merge commit.

      If set, this user is used for the merge commit.  Otherwise, the
      user who triggered the action is used.
    default: ''
  merge-user-email:
    description: >
      The user'email to use for the merge commit.

      If set, this user is used for the merge commit.  Otherwise, the
      user who triggered the action is used.
    default: ''
  comment:
    description: >
      Whether to post a comment.

      If set to true or always, this posts a comment to the pull
      request indicating whether it is possible to fast-forward the
      target branch, and, if merge is true, whether fast forwarding
      succeeded.

      If set to on-error (the default), a comment is only posted if
      an error occurs.

      If false or never, no comment is posted.  The comment is
      still available via the comment output variable, and in the
      step's summary.
    default: on-error
  debug:
    description: >
      Enables debugging output.

      If set to 1 or true, increases the workflow's verbosity.  This
      may also execute some additional RPCs, and so should normally
      be disabled.
    default: 0
outputs:
  comment:
    description: >
      The comment.

      A comment explaining whether fast forwarding is possible, and,
      if `merge` is true, whether it was successful.

      The comment is a JSON document with a single field, `body`.
    value: ${{ steps.fast-forward.outputs.comment }}
runs:
  using: "composite"
  steps:
    - id: fast-forward
      run: |
        export GITHUB_TOKEN=${{ inputs.github_token }}
        export DEBUG=${{ inputs.debug }}
        export COMMENT=${{ inputs.comment }}

        # github.action_path is set to $REPO.
        if test "x${{ inputs.merge }}" = xtrue
        then
            # Define the user information for the merge commit.
            case "${{ inputs.merge-author }}" in
            triggerer)
                USER_NAME="${{ github.event.comment.user.login }}"
                USER_EMAIL="${{ github.event.comment.user.id }}+fast-forward-bot-triggered-by-${{ github.event.comment.user.login }}@users.noreply.github.com"
                ;;
            pr-author)
                USER_NAME="${{ github.event.pull_request.user.login }}"
                USER_EMAIL="${{ github.event.pull_request.user.id }}+fast-forward-bot-on-behalf-of-${{ github.event.pull_request.user.login }}@users.noreply.github.com"
                ;;
            fixed)
                USER_NAME="${{ inputs.merge-user-name }}"
                USER_EMAIL="${{ inputs.merge-user-email }}"
                ;;
            *)  ;;
            esac
            # Set the user for the merge commit.
            case "${{ inputs.merge-author }}" in
            triggerer|pr-author|fixed)
                git config --global user.name "${USER_NAME}"
                git config --global user.email "${USER_EMAIL}"
                ;;
            *)  ;;
            esac

            if test "x${{ inputs.merge-method }}" = xmerge-commit
            then
                MERGE_METHOD=merge-commit
            else
                MERGE_METHOD=fast-forward
            fi

            ${{ github.action_path }}/src/fast-forward.sh --merge "${MERGE_METHOD}"
        else
            ${{ github.action_path }}/src/fast-forward.sh
        fi
      shell: bash
branding:
  icon: 'arrow-up-right'
  color: 'green'
